---
# Copyright (c) 2018, 2019 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

bastion_image_ocid: "{{ lookup('env', 'SAMPLE_OL_IMAGE_OCID') }}"
bastion_shape: "{{ lookup('env', 'SAMPLE_INSTANCE_SHAPE') | default('VM.Standard2.1', true) }}"
bastion_availability_domain: "{{ lookup('env', 'SAMPLE_AD2_NAME') }}"

demo_bastion_subnet_name: "{{demo_var_prefix}}_bastion_subnet"
# no special chars, 1-15 chars only, start with alpha
demo_bastion_subnet_dns_label: "demo{{random_suffix}}bastion"

demo_bastion_instance_name: "{{demo_var_prefix}}_bastion_instance"
# no underscores in host names
demo_bastion_host_name: "{{demo_var_prefix}}-bastion-host"

demo_bastion_subnet_security_list_name: "{{demo_var_prefix}}_bastion_subnet_sec_list"
